Implementation smell,Namespace,Class,File,Method,Description
Long Statement,TestServer,TestService,D:\research\architectureSmells\repos\Astn_JSON-RPC.NET\JsonRpcTest\TestService.cs,throwsException3,The length of the statement  "            JsonRpcContext.SetException(new JsonRpcException(-27000' "This exception was thrown using: JsonRpcContext.Current().SetException()"' null)); " is 140.
Long Statement,JsonRpcTest,Global,D:\research\architectureSmells\repos\Astn_JSON-RPC.NET\JsonRpcTest\Global.asax.cs,PreProcess,The length of the statement  "            // DO NOT do this type of thing in production code. You would be better just checking the parameter inside the JsonRpcMethod. " is 125.
Long Statement,JsonRpcTest,Global,D:\research\architectureSmells\repos\Astn_JSON-RPC.NET\JsonRpcTest\Global.asax.cs,PreProcess,The length of the statement  "                ) return new JsonRpcException(-2' "This exception was thrown using: JsonRpcTest.Global.PreProcess' Not Authenticated"' null); " is 125.
Complex Conditional,JsonRpcTest,Global,D:\research\architectureSmells\repos\Astn_JSON-RPC.NET\JsonRpcTest\Global.asax.cs,PreProcess,The conditional expression  "j == null                   || j[0] == null                  || j[0].Type != Newtonsoft.Json.Linq.JTokenType.String                  || !string.Equals(j[0].ToString()' "GoodPassword"' StringComparison.CurrentCultureIgnoreCase)"  is complex.
Magic Number,TestServer,TestService,D:\research\architectureSmells\repos\Astn_JSON-RPC.NET\JsonRpcTest\TestService.cs,devideByZero,The following statement contains a magic number: var j = 15;
Magic Number,TestServer,TestService,D:\research\architectureSmells\repos\Astn_JSON-RPC.NET\JsonRpcTest\TestService.cs,throwsException2,The following statement contains a magic number: throw new JsonRpcException(-27000' "This exception was thrown using: throw new JsonRpcException()"' null);
Magic Number,TestServer,TestService,D:\research\architectureSmells\repos\Astn_JSON-RPC.NET\JsonRpcTest\TestService.cs,throwsException3,The following statement contains a magic number: JsonRpcContext.SetException(new JsonRpcException(-27000' "This exception was thrown using: JsonRpcContext.Current().SetException()"' null));
Magic Number,TestServer,TestService,D:\research\architectureSmells\repos\Astn_JSON-RPC.NET\JsonRpcTest\TestService.cs,testRecursiveClass,The following statement contains a magic number: var obj = new recursiveClass() { Value1 = 10' Nested1 = new recursiveClass() { Value1 = 5 } };
Magic Number,TestServer,TestService,D:\research\architectureSmells\repos\Astn_JSON-RPC.NET\JsonRpcTest\TestService.cs,testRecursiveClass,The following statement contains a magic number: var obj = new recursiveClass() { Value1 = 10' Nested1 = new recursiveClass() { Value1 = 5 } };
Magic Number,JsonRpcTest,Global,D:\research\architectureSmells\repos\Astn_JSON-RPC.NET\JsonRpcTest\Global.asax.cs,PreProcess,The following statement contains a magic number: return new JsonRpcException(-2' "This exception was thrown using: JsonRpcTest.Global.PreProcess' Not Authenticated"' null);
